'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = (file) => fs.readFileSync(path.join(__dirname, file), 'utf8');
const db = read('db.js');
const server = read('server.js');
const wallet = read('wallet.js');
const sessionStore = read('session-store.js');
const frontend = read('../frontend/app.js');
const transfer = read('solana-transfer.service.js');
const walletSession = read('wallet-session.js');
assert.doesNotMatch(db, /akulupa|Seeded default admin/);
assert.match(db, /ADMIN_USERNAME/);
assert.match(db, /ADMIN_PASSWORD/);
assert.doesNotMatch(server, /dev-secret-change-me/);
assert.match(server, /SESSION_SECRET is required/);
assert.match(server, /req\.session\.regenerate/);
assert.match(server, /too many attempts/);
assert.match(server, /forbidden origin/);
assert.match(server, /Cache-Control', 'no-store/);
assert.doesNotMatch(wallet, /dev-fallback-key/);
assert.match(wallet, /WALLET_ENCRYPTION_KEY is required/);
for (const route of [
  /app\.get\('\/api\/wallets', requireAdmin/,
  /app\.post\('\/api\/wallets\/generate', requireAdmin/,
  /app\.post\('\/api\/wallets\/:id\/reveal', requireAdmin/,
  /app\.put\('\/api\/wallets\/:id', requireAdmin/,
  /app\.delete\('\/api\/wallets\/:id', requireAdmin/,
]) assert.match(server, route);
assert.match(server, /app\.get\('\/health'/);
assert.match(sessionStore, /class SQLiteSessionStore extends session\.Store/);
assert.doesNotMatch(server, /connect-sqlite3/);
assert.match(server, /verifyAdminPassword/);
assert.match(server, /api\/settings\/wallet\/reveal/);
assert.match(wallet, /deriveSolanaKeypair/);
assert.match(wallet, /\[44, 501, 0, 0\]/);
assert.match(db, /mnemonic_enc/);
assert.doesNotMatch(frontend, /api\.get\('\/api\/wallets\/' \+ w\.id \+ '\/reveal'/);
assert.match(frontend, /api\/settings\/wallet/);
assert.match(frontend, /w\.is_main/);
assert.match(frontend, /wallets\/transfer\/confirm/);
assert.match(server, /wallets\/transfer\/preview/);
assert.match(server, /wallets\/transfer\/confirm/);
assert.match(transfer, /simulateTransaction/);
assert.match(transfer, /preview expired or already used/);
assert.match(db, /sol_transfer_log/);
// --- Rotation & session unlock contract ---
assert.match(db, /wallet_rotation_state/);
assert.match(db, /secret_access_log/);
assert.match(db, /rotation_enabled/);
assert.match(server, /wallet-session/);
assert.match(server, /api\/wallets\/session-unlock/);
assert.match(server, /api\/wallets\/session-lock/);
assert.match(server, /api\/wallets\/session-status/);
assert.match(server, /lockAllForUser/);
assert.match(walletSession, /NEVER touch disk/);
assert.match(walletSession, /isUnlocked/);
assert.match(walletSession, /lockAllForUser/);
assert.match(walletSession, /function addKey\(sessionId/);
assert.match(walletSession, /secret\.fill\(0\)/);
assert.doesNotMatch(walletSession, /console\.(log|error|warn)/);
assert.match(server, /reveal_private_key/);
assert.match(server, /reveal_seed_phrase/);
assert.match(server, /app\.post\('\/api\/wallets\/rotation\/next'/);
assert.match(server, /api\/wallets\/rotation\/state/);
assert.match(server, /rotation_enabled/);
assert.match(server, /wallet_rotation_state/);
assert.match(frontend, /loadRotationAddress/);
assert.match(frontend, /rotation\/next/);
assert.match(frontend, /session-unlock/);
assert.match(frontend, /session-lock/);
assert.match(frontend, /sessionUnlocked/);
assert.match(server, /api\/wallets\/rotation\/sweep/);
assert.match(server, /wallet session not unlocked/);
assert.match(transfer, /sweep/);
assert.match(transfer, /balance too low to sweep after fee/);
assert.match(frontend, /tryAutoSweep/);
assert.match(frontend, /rotation\/sweep/);
assert.match(server, /sweep_sign/);
// --- Session-scoped unlock, optional monetization, and one-page dashboard ---
assert.match(walletSession, /SESSION_SCOPED/);
assert.doesNotMatch(walletSession, /TTL_MS|expiresAt|setInterval/);
assert.match(server, /lockAllForUser\(user\.id\)/);
assert.match(server, /api\/settings\/monetization/);
assert.match(server, /commissionRate > 2/);
assert.match(server, /buildMonetizationFields/);
assert.match(server, /rateSetting \?/);
assert.match(server, /validRate/);
assert.match(server, /requireAffiliateId/);
assert.match(server, /Affiliate ID SideShift belum diatur/);
assert.match(server, /commitRotationForAddress\(settleAddress\)/);
assert.match(db, /app_settings/);
assert.match(frontend, /state\.view === 'swap'/);
assert.match(frontend, /positiveBalanceWallets/);
assert.match(frontend, /Komisi dan afiliasi/);
assert.match(frontend, /state\.view = l\.id/);
assert.match(frontend, /Pilih address/);
assert.match(frontend, /Kirim swap/);
assert.match(frontend, /swap-steps/);
assert.match(frontend, /asset-pair/);
assert.doesNotMatch(frontend, /unlocked for 30 minutes/);
console.log('security contract: ok');
